// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {domain} from '../models';

export function ApproveReply(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function ClearActivityLogs(arg1:string):Promise<void>;

export function ClearPolymarketEvents():Promise<void>;

export function CreateAccount(arg1:domain.AccountConfig):Promise<void>;

export function DeleteAccount(arg1:string):Promise<void>;

export function EditReply(arg1:string,arg2:string):Promise<void>;

export function ExportTweets(arg1:string,arg2:string):Promise<void>;

export function ExtractCookies():Promise<domain.BrowserAuth>;

export function GenerateReply(arg1:string,arg2:domain.Tweet):Promise<domain.Reply>;

export function GetAccount(arg1:string):Promise<domain.AccountConfig>;

export function GetAccountStatus(arg1:string):Promise<domain.AccountStatus>;

export function GetAccounts():Promise<Array<domain.AccountConfig>>;

export function GetActionHistory(arg1:string,arg2:number):Promise<Array<domain.TweetActionHistory>>;

export function GetActionStats(arg1:string):Promise<domain.ActionStats>;

export function GetActivityLogs(arg1:string,arg2:number):Promise<Array<domain.ActivityLog>>;

export function GetAllActivityLogs(arg1:number):Promise<Array<domain.ActivityLog>>;

export function GetAppVersion():Promise<string>;

export function GetBrowserPath():Promise<string>;

export function GetConfigPath(arg1:string):Promise<string>;

export function GetDailyStats(arg1:string,arg2:number):Promise<Array<domain.DailyStats>>;

export function GetDataDir():Promise<string>;

export function GetDatabaseInfo():Promise<domain.DatabaseInfo>;

export function GetExportPath(arg1:string):Promise<string>;

export function GetNotificationConfig():Promise<domain.NotificationConfig>;

export function GetPendingActions(arg1:string):Promise<Array<domain.TweetAction>>;

export function GetPendingReplies(arg1:string):Promise<Array<domain.ApprovalQueueItem>>;

export function GetPolymarketConfig():Promise<domain.PolymarketConfig>;

export function GetPolymarketEvents(arg1:domain.PolymarketEventFilter):Promise<Array<domain.PolymarketEvent>>;

export function GetPolymarketSaveFilter():Promise<domain.PolymarketEventFilter>;

export function GetPolymarketWallets(arg1:number):Promise<Array<domain.WalletProfile>>;

export function GetPolymarketWatcherStatus():Promise<domain.PolymarketWatcherStatus>;

export function GetProfileHistory(arg1:string,arg2:number):Promise<Array<domain.ProfileSnapshot>>;

export function GetReplyHistory(arg1:string,arg2:number):Promise<Array<domain.Reply>>;

export function GetReplyPerformance(arg1:string,arg2:number):Promise<domain.ReplyPerformanceReport>;

export function GetTweetDetails(arg1:string,arg2:string):Promise<domain.Tweet>;

export function GetWorkerStatus():Promise<Record<string, boolean>>;

export function ManualSearch(arg1:string,arg2:string,arg3:number):Promise<Array<domain.Tweet>>;

export function OpenFolder(arg1:string):Promise<void>;

export function RejectReply(arg1:string):Promise<void>;

export function ReloadAccount(arg1:string):Promise<domain.AccountConfig>;

export function RestartAccount(arg1:string):Promise<void>;

export function SaveBrowserAuth(arg1:string,arg2:domain.BrowserAuth):Promise<void>;

export function SearchTweets(arg1:string):Promise<Array<domain.Tweet>>;

export function SendTestNotification():Promise<void>;

export function SetNotificationConfig(arg1:domain.NotificationConfig):Promise<void>;

export function SetPolymarketConfig(arg1:domain.PolymarketConfig):Promise<void>;

export function SetPolymarketSaveFilter(arg1:domain.PolymarketEventFilter):Promise<void>;

export function StartAccount(arg1:string):Promise<void>;

export function StartPolymarketWatcher():Promise<void>;

export function StopAccount(arg1:string):Promise<void>;

export function StopPolymarketWatcher():Promise<void>;

export function TestAccountConnection(arg1:string):Promise<void>;

export function TestTweetAction(arg1:string):Promise<void>;

export function UpdateAccount(arg1:domain.AccountConfig):Promise<void>;
