// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveReply(arg1) {
  return window['go']['main']['App']['ApproveReply'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearActivityLogs(arg1) {
  return window['go']['main']['App']['ClearActivityLogs'](arg1);
}

export function ClearPolymarketEvents() {
  return window['go']['main']['App']['ClearPolymarketEvents']();
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function EditReply(arg1, arg2) {
  return window['go']['main']['App']['EditReply'](arg1, arg2);
}

export function ExportTweets(arg1, arg2) {
  return window['go']['main']['App']['ExportTweets'](arg1, arg2);
}

export function ExtractCookies() {
  return window['go']['main']['App']['ExtractCookies']();
}

export function GenerateReply(arg1, arg2) {
  return window['go']['main']['App']['GenerateReply'](arg1, arg2);
}

export function GetAccount(arg1) {
  return window['go']['main']['App']['GetAccount'](arg1);
}

export function GetAccountStatus(arg1) {
  return window['go']['main']['App']['GetAccountStatus'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetActivityLogs(arg1, arg2) {
  return window['go']['main']['App']['GetActivityLogs'](arg1, arg2);
}

export function GetAllActivityLogs(arg1) {
  return window['go']['main']['App']['GetAllActivityLogs'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfigPath(arg1) {
  return window['go']['main']['App']['GetConfigPath'](arg1);
}

export function GetDailyStats(arg1, arg2) {
  return window['go']['main']['App']['GetDailyStats'](arg1, arg2);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDatabaseInfo() {
  return window['go']['main']['App']['GetDatabaseInfo']();
}

export function GetExportPath(arg1) {
  return window['go']['main']['App']['GetExportPath'](arg1);
}

export function GetPendingReplies(arg1) {
  return window['go']['main']['App']['GetPendingReplies'](arg1);
}

export function GetPolymarketConfig() {
  return window['go']['main']['App']['GetPolymarketConfig']();
}

export function GetPolymarketEvents(arg1) {
  return window['go']['main']['App']['GetPolymarketEvents'](arg1);
}

export function GetPolymarketSaveFilter() {
  return window['go']['main']['App']['GetPolymarketSaveFilter']();
}

export function GetPolymarketWallets(arg1) {
  return window['go']['main']['App']['GetPolymarketWallets'](arg1);
}

export function GetPolymarketWatcherStatus() {
  return window['go']['main']['App']['GetPolymarketWatcherStatus']();
}

export function GetProfileHistory(arg1, arg2) {
  return window['go']['main']['App']['GetProfileHistory'](arg1, arg2);
}

export function GetReplyHistory(arg1, arg2) {
  return window['go']['main']['App']['GetReplyHistory'](arg1, arg2);
}

export function GetReplyPerformance(arg1, arg2) {
  return window['go']['main']['App']['GetReplyPerformance'](arg1, arg2);
}

export function GetTweetDetails(arg1, arg2) {
  return window['go']['main']['App']['GetTweetDetails'](arg1, arg2);
}

export function GetWorkerStatus() {
  return window['go']['main']['App']['GetWorkerStatus']();
}

export function ManualSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['ManualSearch'](arg1, arg2, arg3);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function RejectReply(arg1) {
  return window['go']['main']['App']['RejectReply'](arg1);
}

export function ReloadAccount(arg1) {
  return window['go']['main']['App']['ReloadAccount'](arg1);
}

export function RestartAccount(arg1) {
  return window['go']['main']['App']['RestartAccount'](arg1);
}

export function SaveBrowserAuth(arg1, arg2) {
  return window['go']['main']['App']['SaveBrowserAuth'](arg1, arg2);
}

export function SearchTweets(arg1) {
  return window['go']['main']['App']['SearchTweets'](arg1);
}

export function SetPolymarketConfig(arg1) {
  return window['go']['main']['App']['SetPolymarketConfig'](arg1);
}

export function SetPolymarketSaveFilter(arg1) {
  return window['go']['main']['App']['SetPolymarketSaveFilter'](arg1);
}

export function StartAccount(arg1) {
  return window['go']['main']['App']['StartAccount'](arg1);
}

export function StartPolymarketWatcher() {
  return window['go']['main']['App']['StartPolymarketWatcher']();
}

export function StopAccount(arg1) {
  return window['go']['main']['App']['StopAccount'](arg1);
}

export function StopPolymarketWatcher() {
  return window['go']['main']['App']['StopPolymarketWatcher']();
}

export function TestAccountConnection(arg1) {
  return window['go']['main']['App']['TestAccountConnection'](arg1);
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}
